title: Maps
modelClass: Nerdauto\Leafmap\Models\Maps
list: $/nerdauto/leafmap/models/maps/columns.yaml
recordUrl: 'nerdauto/leafmap/maps/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
showSorting: 1
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search.prompt'
